### ISSUE TITLE
Use Unicode character count as fstring length

### ISSUE THREAD

**Issue by greg** [greg/objser#3]
Currently, `fstring` stores its length in bytes, reducing the length of strings containing multi-byte characters that can be stored in this format.

Storing the Unicode character count instead would allow for always storing up to 15 characters, but would force implementations to read the input character by character until termination of the string (an insignificant inconvenience).

Are there any other issues for/against this change?

**Comment by cortices** [comment]
Byte length allows correct allocation and calculation for memory operations. Unicode length is only significant for user experience. Not to mention, it would make the length limit confusing and non obvious. Not to mention, in that case, what's the use of length at all? Given the entire string would have to be processed anyway, having the character length wouldn't even allow any optimisation, whereas byte length does.

**Comment by greg** [comment]
If you have a string with 4 Unicode characters, each of which is 4 bytes, you'd be able to use `fstring` for it if Unicode character count was used, but by byte count it'd be too long and you'd have to use a less space-economical format. That's the main reason for considering this change.

**Comment by cortices** [comment]
That's a ridiculously tiny optimisation to consider compared with the extra O(n) required to unpack every single string.

**Comment by greg** [comment]
The actual time to decode won't change significantly since it's just one more loop over the string to count, but counting Unicode characters may prove problematic in many implementation languages, so for simplicity, the count is best left as byte length.
