### ISSUE TITLE
Explicit file termination/length specifier

### ISSUE THREAD

**Issue by greg** [greg/objser#4]
Currently, EOF or end of stream is the only way to terminate the input. The end of the input is significant as the root primitive is the last primitive that occurs.

Allowing a sentinel byte as an optional terminator could be useful in some situations involving file streams, but would permit placing arbitrary content after the end of the data in a file (a potential security issue).

**Comment by greg** [comment]
More generally, specifying the length at the start of the file would allow validating that the entire stream was received (but would waste bytes). Requiring a sentinel at the end of the file serves the same purpose, wasting only one byte.

**Comment by cortices** [comment]
I believe data compression and error detection & correction is out of scope for the project. Just as adding a checksum of contents is out of scope. If any such things are required, package the file with gzip or something.

**Comment by greg** [comment]
true, this should be left for a possible future extension of the spec that defines a permanent storage format; the current focus is data transmission
